### ISSUE TITLE
indentation of dune-project files

### ISSUE THREAD

**Issue by nilsbecker** [rgrinberg/vim-ocaml#34]
i get this indentation:
```
(lang dune 1.10)
(generate_opam_files true)

	(name "extract_codes")
	(maintainers "nils@localhost")
	(package
	 (name "extract_codes")
	 (synopsis "bla")
	 (description "bla bla")
	 (depends
		(gen (> 0.5))
		(containers (>= 2.5 ))
		(yojson (>= 1.7.0))
		(csv (>= 2.2))))
```

which seems odd. is this intended? the file type is recognized as dune-project, correctly. or is this not a vim-ocaml issue? i also have the plugin ocp-indent-vim installed.

**Comment by copy** [comment]
Previously there were no specific rules for dune files, so it was falling back to vim defaults, which seems to be tabs.

Thanks for reporting.
