### ISSUE TITLE
do not always indent after `->`

### ISSUE THREAD

**Issue by c-cube** [rgrinberg/vim-ocaml#7]
Line 103 of `indent` there seems to be a test for lines ending with `->`, such as those found in `.mli` file for long signatures.

I tend to indent like this:

```ocaml
val f :
  foo ->
  bar ->
  baaz
```

but vim really wants me to indent after each arrow. Is it possible to add a configuration flag for toggling this  behavior?

**Comment by hcarty** [comment]
Maybe this could be handled as a `.ml` vs `.mli` indentation difference.  Without the kind of context tracking performed by ocp-indent it would be difficult to tell in a `.ml` if you're looking at a type or a definition like `fun x ->`.

**Comment by c-cube** [comment]
Oh, I didn't even think of `fun x ->\n...`. Indeed it could be based on the file extension, since those are very different arrows…

**Comment by rgrinberg** [comment]
it would have to a little cleverer than that to be really robust. You can also have such arrows in `sig ... end`

**Comment by hcarty** [comment]
And long inline type signatures.  Being really robust eventually leads to ocp-indent in vimscript! :-)

**Comment by c-cube** [comment]
so I suppose I should give up and use the ocp-indent vim plugin…

**Comment by rgrinberg** [comment]
I think that would be wise regardless of the outcome of this ticket. What are you reasons for not using ocp-indent?

**Comment by c-cube** [comment]
well I had trouble with it a long time ago, and never took time to configure it. But I'm going to try again.
